#!/bin/bash

# Fix dash to panel refusing to load default icon
dashicondefault="'/usr/share/pixmaps/slimbook-distributor-logo.png'"
dashicon=`gsettings get org.gnome.shell.extensions.dash-to-panel show-apps-icon-file`

if [ "$dashicon" = "$dashicondefault" ]; then
	gsettings set org.gnome.shell.extensions.dash-to-panel show-apps-icon-file $dashicondefault
fi
