#!/bin/bash

# Fix dash to panel refusing to load default icon
dashicondefault="'/usr/share/pixmaps/slimbook-distributor-logo.png'"
dashicon=`gsettings get org.gnome.shell.extensions.dash-to-panel show-apps-icon-file`

if [ "$dashicon" = "$dashicondefault" ]; then
	gsettings set org.gnome.shell.extensions.dash-to-panel show-apps-icon-file $dashicondefault
fi

value=`gsettings get org.gnome.shell.extensions.dash-to-panel group-apps`
gsettings set org.gnome.shell.extensions.dash-to-panel group-apps $value

value=`gsettings get org.gnome.shell.extensions.dash-to-panel animate-appicon-hover`
gsettings set org.gnome.shell.extensions.dash-to-panel animate-appicon-hover $value

value=`gsettings get org.gnome.shell.extensions.dash-to-panel group-apps-underline-unfocused`
gsettings set org.gnome.shell.extensions.dash-to-panel group-apps-underline-unfocused $value

value=`gsettings get org.gnome.shell.extensions.dash-to-panel group-apps-use-launchers`
gsettings set org.gnome.shell.extensions.dash-to-panel group-apps-use-launchers $value
