#!/bin/bash

source /usr/share/slimbook-console/trueline.sh

family=`slimbookctl info | grep family | cut -d ":" -f 2`

case $family in

    "executive")
        name="Slimbook Executive"
    ;;

    "prox")
        name="Slimbook ProX"
    ;;

    "titan")
        name="Slimbook Titan"
    ;;

    "hero")
        name="Slimbook Hero"
    ;;

    "essential")
        name="Slimbook Essential"
    ;;

    "elemental")
        name="Slimbook Elemental"
    ;;

    "excalibur")
        name="Slimbook Excalibur"
    ;;

    "hero-s")
        name="Slimbook Hero-S"
    ;;

    "zero")
        name="Slimbook Zero"
    ;;

    "one")
        name="Slimbook One"
    ;;

    "nas")
        name="Slimbook NAS"
    ;;

    "unknown")
    ;;

    *)
        name=$family
    ;;

esac

if [ ! -z "$name" ]; then
    echo -e "Welcome to \e[34mSlimbook OS 24\e[0m powered by \e[34m${name}\e[0m\n"
else
    echo -e "Welcome to \e[34mSlimbook OS 24\e[0m\n"
fi
